openapi: 3.1.0
info:
  title: API сервер для проекта «Что посмотреть».
  description: |-
    * Список ресурсов и маршрутов сервера «Что посмотреть».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: films
    description: Действия с фильмами.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.
paths:
  /films:
    post:
      tags:
        - films
      summary: Добавление фильма
      description: Добавляет новый фильм

      requestBody:
        description: Информация для создания нового фильма
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOrUpdateFilm"
        required: true

      responses:
        "201":
          description: Фильм создан. Объект фильма.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"

        "400":
          description: Данные не валидны.

        "401":
          description: Пользователь не авторизован.

    get:
      tags:
        - films
      summary: Получение списка фильмов
      description: Получает список фильмов

      parameters:
        - name: limit
          in: query
          description: Максимальное количество возвращаемых фильмов
          schema:
            type: number
            example: 60

      responses:
        "200":
          description: Возвращает массив фильмов.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/films"

  /films/genres/{genre}:
    get:
      tags:
        - films
      summary: Получение списка фильмов определённого жанра
      description: Получает список фильмов определённого жанра

      parameters:
        - name: genre
          in: path
          description: Определённый жанр фильмов
          required: true
          schema:
            type: string
            example: Drama

        - name: limit
          in: query
          description: Максимальное количество возвращаемых фильмов
          schema:
            type: number
            example: 100

      responses:
        "200":
          description: Возвращает массив фильмов определённого жанра.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/films"

        "404":
          description: Такой жанр не существует


  /films/{filmId}:
    patch:
      tags:
        - films
      summary: Редактирование фильма
      description: Редактирует карточку фильма

      parameters:
        - name: filmId
          in: path
          description: Уникальный идентификатор фильма
          required: true
          schema:
            type: number
            example: 1


      requestBody:
        description: Информация для редактирования фильма
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOrUpdateFilm"
        required: true

      responses:
        "200":
          description: Фильм изменён. Объект фильма.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"

        "400":
          description: Данные не валидны.

        "401":
          description: Пользователь не авторизован.

        "403":
          description: Недостаточно прав для редактирования фильма.

        "404":
          description: Такой фильм не существует

    delete:
      tags:
        - films
      summary: Удаление фильма
      description: Удаляет карточку фильма

      responses:
        "204":
          description: Фильм удалён.

        "401":
          description: Пользователь не авторизован.

        "403":
          description: Недостаточно прав для удаления фильма.

        "404":
          description: Такой фильм не существует

    get:
      tags:
        - films
      summary: Получение детальной информации по фильму
      description: Получает детальную информацию по фильму

      responses:
        "200":
          description: Возвращает детальную информацию по фильму.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"

        "404":
          description: Такой фильм не существует


  /films/promo:
    get:
      tags:
        - films
      summary: Получение промо-фильма
      description: Получает промо-фильм

      responses:
        "200":
          description: Возвращает объект промо-фильма.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"

  /films/favorite:
    get:
      tags:
        - films
      summary: Получение списка фильмов "К просмотру"
      description: Получает список фильмов "К просмотру"

      responses:
        "200":
          description: Возвращает массив фильмов, добавленных в список "К просмотру"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/films"

        "401":
          description: Пользователь не авторизован.

  /films/favorite/{filmId}/{status}:
    post:
      tags:
        - films
      summary: Добавление/удаление фильма из списка "К просмотру"
      description: Добавляет/удаляет фильма из списка "К просмотру"

      parameters:
        - name: filmId
          in: path
          description: Уникальный идентификатор фильма
          required: true
          schema:
            type: number
            example: 1

        - name: status
          in: path
          description: Статус фильма. Может быть 1 или 0, где 1 добавляет фильма в список «к просмотру», а 0 удаляет
          required: true
          schema:
            type: number
            example: 1

      responses:
        "200":
          description: Объект фильма
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/film"

        "401":
          description: Пользователь не авторизован.

        "404":
          description: Такой фильм не существует

  /films/{filmId}/comments:
    get:
      tags:
        - comments
      summary: Получение списка комментариев для определенного фильма
      description: Получает список комментариев для определенного фильма

      parameters:
        - name: filmId
          in: path
          description: Уникальный идентификатор фильма
          required: true
          schema:
            type: number
            example: 1

      responses:
        "200":
          description: Массив комментариев
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comments"

        "404":
          description: Такой фильм не существует.

  /comments:
    post:
      tags:
        - comments
      summary: Добавление нового комментария к определённому фильму
      description: Добавляет новый комментарий к определённому фильму

      parameters:
        - name: filmId
          in: path
          description: Уникальный идентификатор фильма
          required: true
          schema:
            type: number
            example: 1

      requestBody:
        description: Информация для создания нового комментария
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createComment"
        required: true

      responses:
        "201":
          description: Комментарий создан. Объект комментария.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment"

        "400":
          description: Данные не валидны.

        "401":
          description: Пользователь не авторизован.

        "404":
          description: Такой фильм не существует


  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя.

      requestBody:
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createUser"
        required: true

      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"

        "400":
          description: Логин или пароль не валидны.

        "409":
          description: Пользователь с таким email уже существует.

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля

      requestBody:
        description: Информация для авторизации.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"
        required: true

      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userWithToken"

        "400":
          description: Логин или пароль неверный.

        "404":
          description: Пользователь с таким логином не существует

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю

      responses:
        "200":
          description: Пользователь авторизован. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userWithToken"

        "401":
          description: Пользователь не авторизован.

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить изображение аватара
      description: Загружает изображение аватара пользователя. Изображение
        аватара должно быть в формате `png` или `jpg`.

      parameters:
        - name: userId
          in: path
          description: Уникальный идентификатор пользователя
          required: true
          schema:
            type: number
            example: 1

      responses:
        "201":
          description: Пользователь изменен. Объект пользователя.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userWithToken"

        "400":
          description: Некорректный формат изображения

        "404":
          description: Пользователь с таким логином не существует.


components:
  schemas:
    createOrUpdateFilm:
      type: object

      properties:
        name:
          type: string
          example: Matrix

        description:
          type: string
          example: A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.

        genre:
          type: string
          example: Drama

        released:
          type: number
          example: 2010

        previewVideoLink:
          type: string
          example: https://11.react.pages.academy/static/film/video/traffic.mp4

        videoLink:
          type: string
          example: https://11.react.pages.academy/static/film/video/bubbles.mp4

        starring:
          type: array
          items:
            type: string
            example: Bruce Willis

        director:
          type: string
          example: Quentin Tarantino

        runTime:
          type: number
          example: 130

        posterImage:
          type: string
          example: https://11.react.pages.academy/static/film/poster/matrix.jpg

        backgroundImage:
          type: string
          example: https://11.react.pages.academy/static/film/background/matrix.jpg

        backgroundColor:
          type: string
          example: '#B9B27E'

    film:
      type: object

      properties:
        name:
          type: string
          example: Matrix

        description:
          type: string
          example: A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.

        postDate:
          type: string
          format: date-time
          example: 2022-12-22T08:45:40.283Z

        genre:
          type: string
          example: Drama

        released:
          type: number
          example: 2010

        rating:
          type: number
          example: 0

        previewVideoLink:
          type: string
          example: https://11.react.pages.academy/static/film/video/traffic.mp4

        videoLink:
          type: string
          example: https://11.react.pages.academy/static/film/video/bubbles.mp4

        starring:
          type: array
          items:
            type: string
            example: Bruce Willis

        director:
          type: string
          example: Quentin Tarantino

        runTime:
          type: number
          example: 130

        commentsAmount:
          type: number
          example: 110

        userId:
          type: string
          example: 6317c3d6a54ab1061c6434ea

        posterImage:
          type: string
          example: https://11.react.pages.academy/static/film/poster/matrix.jpg

        backgroundImage:
          type: string
          example: https://11.react.pages.academy/static/film/background/matrix.jpg

        backgroundColor:
          type: string
          example: '#B9B27E'


    films:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: Matrix

          postDate:
            type: string
            format: date-time
            example: 2022-12-22T08:45:40.283Z

          genre:
            type: string
            example: Drama

          previewVideoLink:
            type: string
            example: https://11.react.pages.academy/static/film/video/traffic.mp4

          userId:
            type: string
            example: 6317c3d6a54ab1061c6434ea

          posterImage:
            type: string
            example: https://11.react.pages.academy/static/film/poster/matrix.jpg

          commentsAmount:
            type: number
            example: 110

    comments:
      type: array
      items:
        type: object
        properties:
          message:
            type: string
            example: Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the director's funniest and most exquisitely designed movies in years.

          rating:
            type: number
            example: 7.8

          postDate:
            type: string
            format: date-time
            example: 2022-12-22T08:45:40.283Z

          userId:
            type: string
            example: 6317c3d6a54ab1061c6434ea

    createComment:
      type: object

      properties:
          message:
            type: string
            example: Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the director's funniest and most exquisitely designed movies in years.

          rating:
            type: number
            example: 7.8

    comment:
      type: object
      properties:
        message:
          type: string
          example: Discerning travellers and Wes Anderson fans will luxuriate in the glorious Mittel-European kitsch of one of the director's funniest and most exquisitely designed movies in years.

        rating:
          type: number
          example: 7.8

        postDate:
          type: string
          format: date-time
          example: 2022-12-22T08:45:40.283Z

        userId:
          type: string
          example: 6317c3d6a54ab1061c6434ea


    createUser:
      type: object

      properties:
        email:
          type: string
          example: test@lost.local

        userName:
          type: string
          example: Emilia

        password:
          type: string
          example: 123456

    loginUser:
      type: object

      properties:
        email:
          type: string
          example: Emilia@outlook.com

        password:
          type: string
          example: 123456

    user:
      type: object

      properties:
        id:
          type: string
          example: 6317c3d6a54ab1061c6434ea

        userName:
          type: string
          example: Emilia

        email:
          type: string
          example: test@lost.local

        avatarUrl:
          type: string
          example: user.jpg


    userWithToken:
      type: object

      properties:
        id:
          type: string
          example: 6317c3d6a54ab1061c6434ea

        userName:
          type: string
          example: Emilia

        email:
          type: string
          example: test@lost.local

        avatarUrl:
          type: string
          example: user.jpg

        token:
          type: string
          example: T2xpdmVyLmNvbm5lckBnbWFpbC5jb20=